param (
    [string]$hjsonPath,
    [string]$outputPath
)

if (-not (Test-Path $hjsonPath)) { exit }

$content = Get-Content $hjsonPath -Raw

# Basic parser for HJSON keys and categories
$lines = $content -split "`r`n|`n"
$currentClass = ""
$entries = @{}

foreach ($line in $lines) {
    $trimmed = $line.Trim()

    # Skip empty lines and comment lines
    if ([string]::IsNullOrWhiteSpace($trimmed) -or $trimmed.StartsWith("#") -or $trimmed.StartsWith("//")) {
        continue
    }
    
    # Match block headers (e.g., Extras: { or Mods.TerraStorageOverflow.Extras: {)
    if ($trimmed -match '([a-zA-Z0-9_\.]+)\s*:\s*\{') {
        $fullPath = $matches[1]
        $currentClass = $fullPath -split '\.' | Select-Object -Last 1
        if (-not $entries.ContainsKey($currentClass)) {
            $entries[$currentClass] = @()
        }
    }
    # Match key-value pairs (e.g., SelectModeHeader: "...")
    elseif ($trimmed -match '^([a-zA-Z0-9_]+)\s*:\s*(.*)$' -and $currentClass) {
        $key = $matches[1]
        $val = $matches[2].Trim().TrimEnd(',')

        if ($key -ne "DisplayName" -and $key -ne "Label" -and $key -ne "Tooltip") {
            # Strip outer quotes if present
            if (($val.StartsWith('"') -and $val.EndsWith('"')) -or ($val.StartsWith("'") -and $val.EndsWith("'"))) {
                if ($val.Length -ge 2) {
                    $val = $val.Substring(1, $val.Length - 2)
                }
            }

            $entries[$currentClass] += [PSCustomObject]@{
                Key   = $key
                Value = $val
            }
        }
    }
}

# Generate C# class
$sb = [System.Text.StringBuilder]::new()
$null = $sb.AppendLine("// <auto-generated />")
$null = $sb.AppendLine("using Terraria.Localization;")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("namespace TerraStorageOverflow.Common.Utils")
$null = $sb.AppendLine("{")
$null = $sb.AppendLine("    public static class Loca")
$null = $sb.AppendLine("    {")
$null = $sb.AppendLine('        private const string Prefix = "Mods.TerraStorageOverflow.";')
$null = $sb.AppendLine('        private static string Get(string key, params object[] args) => Language.GetTextValue(Prefix + key, args);')
$null = $sb.AppendLine("")

foreach ($category in $entries.Keys) {
    # Skip generating the class if it has no valid keys
    if ($entries[$category].Count -eq 0) { continue }

    $null = $sb.AppendLine("        public static class $category")
    $null = $sb.AppendLine("        {")
    foreach ($item in $entries[$category]) {
        $k = $item.Key
        # Escape XML characters for safe docstrings (<, >, &, etc.)
        $safeVal = [System.Security.SecurityElement]::Escape($item.Value)

        $null = $sb.AppendLine("            /// <summary>")
        $null = $sb.AppendLine("            /// $safeVal")
        $null = $sb.AppendLine("            /// </summary>")
        $null = $sb.AppendLine("            public static string $k => Get(`"$category.$k`");")
    }
    $null = $sb.AppendLine("        }")
}

$null = $sb.AppendLine("    }")
$null = $sb.AppendLine("}")

Set-Content -Path $outputPath -Value $sb.ToString()