param (
    [string]$hjsonPath,
    [string]$outputPath
)

if (-not (Test-Path $hjsonPath)) { exit }

$content = Get-Content $hjsonPath -Raw
$lines = $content -split "`r`n|`n"

$scopeStack = [System.Collections.Generic.Stack[string]]::new()
$entries = [ordered]@{}

$inMultiline = $false
$multilineKey = ""
$multilineValue = ""
$pendingKey = ""

foreach ($line in $lines) {
    $trimmed = $line.Trim()

    # Handle active multiline block continuation
    if ($inMultiline) {
        if ($trimmed -match '(.*?)(?:''{3}|"{3})\s*,?\s*$') {
            $lineContent = $matches[1].Trim()
            if ($lineContent) { 
                $multilineValue += if ($multilineValue) { "`n" + $lineContent } else { $lineContent }
            }
            
            $currentClass = $scopeStack.Peek()
            
            if ($multilineKey -notmatch '^(DisplayName|Label|Tooltip)$') {
                $entries[$currentClass] += [PSCustomObject]@{
                    Key   = $multilineKey
                    Value = $multilineValue.Trim()
                }
            }
            
            $inMultiline = $false
            $multilineKey = ""
            $multilineValue = ""
        } else {
            if ($trimmed) { 
                $multilineValue += if ($multilineValue) { "`n" + $trimmed } else { $trimmed }
            }
        }
        continue
    }

    # Skip empty lines and standalone comments outside multiline
    if ([string]::IsNullOrWhiteSpace($trimmed) -or $trimmed.StartsWith("#") -or $trimmed.StartsWith("//")) {
        continue
    }

    # Handle closing braces
    if ($trimmed -eq '}' -or $trimmed -eq '},') {
        if ($scopeStack.Count -gt 0) { $null = $scopeStack.Pop() }
        $pendingKey = ""
        continue
    }

    # Match block headers (e.g. Extras: {)
    if ($trimmed -match '^([a-zA-Z0-9_\.]+)\s*:\s*\{') {
        $fullPath = $matches[1]
        $className = $fullPath -split '\.' | Select-Object -Last 1
        $scopeStack.Push($className)

        if (-not $entries.Contains($className)) {
            $entries[$className] = @()
        }
        $pendingKey = ""
        continue
    }

    # Handle multiline string starting on line following a pending key
    if ($pendingKey -and $trimmed -match '^(?:''{3}|"{3})') {
        $rest = $trimmed -replace '^(?:''{3}|"{3})', ''
        $currentClass = $scopeStack.Peek()

        if ($rest -match '(.*?)(?:''{3}|"{3})\s*,?\s*$') {
            $cleanVal = $matches[1].Trim()
            if ($pendingKey -notmatch '^(DisplayName|Label|Tooltip)$') {
                $entries[$currentClass] += [PSCustomObject]@{
                    Key   = $pendingKey
                    Value = $cleanVal
                }
            }
        } else {
            $inMultiline = $true
            $multilineKey = $pendingKey
            $multilineValue = $rest.Trim()
        }
        $pendingKey = ""
        continue
    }

    # Handle unquoted value on line following a pending key
    if ($pendingKey) {
        $val = $trimmed.TrimEnd(',')
        $currentClass = $scopeStack.Peek()
        if ($pendingKey -notmatch '^(DisplayName|Label|Tooltip)$') {
            $entries[$currentClass] += [PSCustomObject]@{
                Key   = $pendingKey
                Value = $val
            }
        }
        $pendingKey = ""
        continue
    }

    # Match key-value declarations
    if ($trimmed -match '^([a-zA-Z0-9_]+)\s*:\s*(.*)$' -and $scopeStack.Count -gt 0) {
        $key = $matches[1]
        $val = $matches[2].Trim()

        if ($val -eq '{') { continue }

        $currentClass = $scopeStack.Peek()

        if ($val -eq '') {
            $pendingKey = $key
        } elseif ($val -match '^(?:''{3}|"{3})') {
            $rest = $val -replace '^(?:''{3}|"{3})', ''
            
            if ($rest -match '(.*?)(?:''{3}|"{3})\s*,?\s*$') {
                $cleanVal = $matches[1].Trim()
                if ($key -notmatch '^(DisplayName|Label|Tooltip)$') {
                    $entries[$currentClass] += [PSCustomObject]@{
                        Key   = $key
                        Value = $cleanVal
                    }
                }
            } else {
                $inMultiline = $true
                $multilineKey = $key
                $multilineValue = $rest.Trim()
            }
        } else {
            if ($key -notmatch '^(DisplayName|Label|Tooltip)$') {
                if (($val.StartsWith('"') -and $val.EndsWith('"')) -or ($val.StartsWith("'") -and $val.EndsWith("'"))) {
                    if ($val.Length -ge 2) { $val = $val.Substring(1, $val.Length - 2) }
                }
                $val = $val.TrimEnd(',')

                $entries[$currentClass] += [PSCustomObject]@{
                    Key   = $key
                    Value = $val
                }
            }
        }
    }
}

# Generate C# class
$sb = [System.Text.StringBuilder]::new()
$null = $sb.AppendLine("// <auto-generated />")
$null = $sb.AppendLine("using Terraria.Localization;")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("namespace TerraStorageOverflow.Common.Utils")
$null = $sb.AppendLine("{")
$null = $sb.AppendLine("    public static class Loca")
$null = $sb.AppendLine("    {")
$null = $sb.AppendLine('        private const string Prefix = "Mods.TerraStorageOverflow.";')
$null = $sb.AppendLine('        private static string Get(string key, params object[] args) => Language.GetTextValue(Prefix + key, args);')
$null = $sb.AppendLine("")

foreach ($category in $entries.Keys) {
    if ($entries[$category].Count -eq 0) { continue }

    $null = $sb.AppendLine("        public static class $category")
    $null = $sb.AppendLine("        {")
    foreach ($item in $entries[$category]) {
        $k = $item.Key

        $null = $sb.AppendLine("            /// <summary>")
        
        # Split multiline values across multiple doc comment lines
        $valLines = $item.Value -split "`r`n|`n"
        foreach ($vLine in $valLines) {
            $safeVal = [System.Security.SecurityElement]::Escape($vLine)
            $null = $sb.AppendLine("            /// $safeVal")
        }

        $null = $sb.AppendLine("            /// </summary>")

        if ($item.Value -match '\{[0-9]+\}') {
            $null = $sb.AppendLine("            public static string $k(params object[] args) => Get(""$category.$k"", args);")
        } else {
            $null = $sb.AppendLine("            public static string $k => Get(""$category.$k"");")
        }
    }
    $null = $sb.AppendLine("        }")
}

$null = $sb.AppendLine("    }")
$null = $sb.AppendLine("}")

Set-Content -Path $outputPath -Value $sb.ToString()