<Project Sdk="Microsoft.NET.Sdk">
  <!-- Import tModLoader mod properties -->
  <Import Project="..\tModLoader.targets" />

  <!-- General -->
  <PropertyGroup></PropertyGroup>

  <ItemGroup>
    <Reference Include="TerraStorage">
      <HintPath>G:\Documents\My Games\Terraria\tModLoader\ModSources\TerraStorageOverflow\Lib\TerraStorage.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="GenerateLoca" BeforeTargets="BeforeBuild">
    <Exec Command="powershell -ExecutionPolicy Bypass -File &quot;$(ProjectDir)GenerateLoca.ps1&quot; &quot;$(ProjectDir)Localization\en-US_Mods.TerraStorageOverflow.hjson&quot; &quot;$(ProjectDir)Common\Utils\Loca.g.cs&quot;" />
  </Target>
</Project>
