// <auto-generated />
using Terraria.Localization;

namespace TerraStorageOverflow.Common.Utils
{
    internal static class Loca
    {
        private const string Prefix = "Mods.TerraStorageOverflow.";
        private static string Get(string key, params object[] args) => Language.GetTextValue(Prefix + key, args);

        internal static class EasyLoca
        {
            /// <summary>
            /// Populate
            /// </summary>
            public static string PopulateCraftingCoreButtonText => Get("EasyLoca.PopulateCraftingCoreButtonText");
            /// <summary>
            /// Automatically fetch all stations that would fullfil new conditions for crafting
            /// If a station would fullfil a role already populated (and provide a new one), it will replace it.
            /// </summary>
            public static string PopulateCraftingCoreButtonTooltip => Get("EasyLoca.PopulateCraftingCoreButtonTooltip");
            /// <summary>
            /// Sell Report :
            /// </summary>
            public static string SellReportHeader => Get("EasyLoca.SellReportHeader");
            /// <summary>
            /// Select Duplicate Selling Mode:
            /// </summary>
            public static string SelectModeHeader => Get("EasyLoca.SelectModeHeader");
            /// <summary>
            /// Keep Most Expensive
            /// </summary>
            public static string ModeKeepBest => Get("EasyLoca.ModeKeepBest");
            /// <summary>
            /// Compares duplicate items by monetary value.
            /// Keeps the single best version and sells all lower-tier duplicates.
            /// </summary>
            public static string ModeKeepBestTooltip => Get("EasyLoca.ModeKeepBestTooltip");
            /// <summary>
            /// Keep First Found
            /// </summary>
            public static string ModeKeepFirst => Get("EasyLoca.ModeKeepFirst");
            /// <summary>
            /// Keeps the very first instance found in your storage system
            /// and sells every other duplicate regardless of prefix.
            /// </summary>
            public static string ModeKeepFirstTooltip => Get("EasyLoca.ModeKeepFirstTooltip");
            /// <summary>
            /// Keep One Of Each Prefix
            /// </summary>
            public static string ModeExactMatches => Get("EasyLoca.ModeExactMatches");
            /// <summary>
            /// Only sells items if they match both Item ID AND Prefix.
            /// (It&apos;ll keep one of each item with a unique combination of Item ID and Prefix).
            /// </summary>
            public static string ModeExactMatchesTooltip => Get("EasyLoca.ModeExactMatchesTooltip");
            /// <summary>
            /// Sell Duplicate Items
            /// </summary>
            public static string SellActionButton => Get("EasyLoca.SellActionButton");
            /// <summary>
            /// No items sold yet.
            /// </summary>
            public static string ReportNoItems => Get("EasyLoca.ReportNoItems");
            /// <summary>
            /// No duplicates found to sell.
            /// </summary>
            public static string ReportNoDuplicates => Get("EasyLoca.ReportNoDuplicates");
            /// <summary>
            /// Sold {0} items for {1}
            /// </summary>
            public static string ReportSummary(params object[] args) => Get("EasyLoca.ReportSummary", args);
            /// <summary>
            /// Extras
            /// </summary>
            public static string ExtrasTabName => Get("EasyLoca.ExtrasTabName");
            /// <summary>
            /// Unlocked chest {0}{1} using {2}{3} from remote networks
            /// </summary>
            public static string ChestUnlockMessage(params object[] args) => Get("EasyLoca.ChestUnlockMessage", args);
            /// <summary>
            /// Failed to unlock chest {0}{1} using {2}{3} from remote networks
            /// </summary>
            public static string ChestUnlockFailedMessage(params object[] args) => Get("EasyLoca.ChestUnlockFailedMessage", args);
            /// <summary>
            /// Fishing
            /// </summary>
            public static string CategoryFishing => Get("EasyLoca.CategoryFishing");
            /// <summary>
            /// Clicker Weapons
            /// </summary>
            public static string CategoryClicker => Get("EasyLoca.CategoryClicker");
            /// <summary>
            /// Capture Weapons
            /// </summary>
            public static string CategoryCaptureDisc => Get("EasyLoca.CategoryCaptureDisc");
            /// <summary>
            /// Pets &amp; Mounts
            /// </summary>
            public static string CategoryPets => Get("EasyLoca.CategoryPets");
            /// <summary>
            /// Bound to :
            /// </summary>
            public static string RemoteTooltipBound => Get("EasyLoca.RemoteTooltipBound");
            /// <summary>
            /// Not bound to a network
            /// </summary>
            public static string RemoteTooltipUnbound => Get("EasyLoca.RemoteTooltipUnbound");
            /// <summary>
            /// Storage :
            /// </summary>
            public static string RemoteTooltipCapacity => Get("EasyLoca.RemoteTooltipCapacity");
        }
    }
}

