// <auto-generated />
using Terraria.Localization;

namespace TerraStorageOverflow.Common.Utils
{
    public static class Loca
    {
        private const string Prefix = "Mods.TerraStorageOverflow.";
        private static string Get(string key, params object[] args) => Language.GetTextValue(Prefix + key, args);

        public static class EasyLoca
        {
            /// <summary>
            /// Populate
            /// </summary>
            public static string PopulateCraftingCoreButtonText => Get("EasyLoca.PopulateCraftingCoreButtonText");
            /// <summary>
            /// 
            /// </summary>
            public static string PopulateCraftingCoreButtonTooltip => Get("EasyLoca.PopulateCraftingCoreButtonTooltip");
            /// <summary>
            /// Sell Report :
            /// </summary>
            public static string SellReportHeader => Get("EasyLoca.SellReportHeader");
            /// <summary>
            /// Select Duplicate Selling Mode:
            /// </summary>
            public static string SelectModeHeader => Get("EasyLoca.SelectModeHeader");
            /// <summary>
            /// Keep Most Expensive
            /// </summary>
            public static string ModeKeepBest => Get("EasyLoca.ModeKeepBest");
            /// <summary>
            /// 
            /// </summary>
            public static string ModeKeepBestTooltip => Get("EasyLoca.ModeKeepBestTooltip");
            /// <summary>
            /// Keep First Found
            /// </summary>
            public static string ModeKeepFirst => Get("EasyLoca.ModeKeepFirst");
            /// <summary>
            /// 
            /// </summary>
            public static string ModeKeepFirstTooltip => Get("EasyLoca.ModeKeepFirstTooltip");
            /// <summary>
            /// Keep One Of Each Prefix
            /// </summary>
            public static string ModeExactMatches => Get("EasyLoca.ModeExactMatches");
            /// <summary>
            /// 
            /// </summary>
            public static string ModeExactMatchesTooltip => Get("EasyLoca.ModeExactMatchesTooltip");
            /// <summary>
            /// Sell Duplicate Items
            /// </summary>
            public static string SellActionButton => Get("EasyLoca.SellActionButton");
            /// <summary>
            /// No items sold yet.
            /// </summary>
            public static string ReportNoItems => Get("EasyLoca.ReportNoItems");
            /// <summary>
            /// No duplicates found to sell.
            /// </summary>
            public static string ReportNoDuplicates => Get("EasyLoca.ReportNoDuplicates");
            /// <summary>
            /// Sold {0} items for {1}
            /// </summary>
            public static string ReportSummary(params object[] args) => Get("EasyLoca.ReportSummary", args);
            /// <summary>
            /// Extras
            /// </summary>
            public static string ExtrasTabName => Get("EasyLoca.ExtrasTabName");
            /// <summary>
            /// Unlocked chest {0}{1} using {2}{3} from remote networks
            /// </summary>
            public static string ChestUnlockMessage(params object[] args) => Get("EasyLoca.ChestUnlockMessage", args);
            /// <summary>
            /// Failed to unlock chest {0}{1} using {2}{3} from remote networks
            /// </summary>
            public static string ChestUnlockFailedMessage(params object[] args) => Get("EasyLoca.ChestUnlockFailedMessage", args);
        }
    }
}

